name: module3_task0

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Position in correct directory and make help
      run: cd module3_task0 && make help
